#!/usr/bin/env ruby

require 'optparse'

formulae = []
formulae_upcoming = []
must_find = [

]
must_not_find = [
  /bottle :unneeded/,
  /:x86_64_linux/,
]

parser = OptionParser.new
parser.on("-o", "--online", "check core tap PRs") do
  suffix = ": Build a bottle for Linuxbrew"

  `hub pr list --format '%t%n'`.each_line do |line|
    line = line.chomp
    formulae_upcoming << line.delete_suffix(suffix) if line =~ /.*#{suffix}/
  end
end
parser.on("-m", "--must-find PATTERN", "must find this pattern in file") do |pattern|
  must_find << Regexp.new(pattern)
end
parser.on("-n", "--must-not-find PATTERN", "must not find this pattern in file") do |pattern|
  must_not_find << Regexp.new(pattern)
end
parser.parse!

Dir['Formula/*'].each do |file|
  content = File.read(file)

  found = 0
  must_not_find.each do |pattern|
    found += 1 if content.match?(pattern)
  end

  next if found > 0

  found = must_find.length
  must_find.each do |pattern|
    found -= 1 if content.match?(pattern)
  end

  next if found > 0

  formulae << file.delete_prefix("Formula/").delete_suffix(".rb")
end

formulae = formulae - formulae_upcoming
formulae = formulae.sort
formulae.map { |formula| puts formula }
