#!/bin/bash

set -euo pipefail

cd "$(brew --repository homebrew/core)"

HOMEBREW_BOTTLE_DOMAIN=https://linuxbrew.bintray.com \
    brew pull \
        --bottle \
        --bintray-org=linuxbrew \
        --test-bot-user=LinuxbrewTestBot \
        "$1"

brew squash-bottle-pr
