#!/usr/bin/env -S brew ruby

module Homebrew
  module_function

  # Formula name needs to be passed as first argument
  formula = ARGV.first

  # Get livecheck info
  json = Utils.popen_read HOMEBREW_BREW_FILE, 'livecheck',
                          '--quiet',
                          '--newer-only',
                          '--full-name',
                          '--json',
                          formula

  # Parse livecheck output
  json = JSON.parse json

  # Exit if empty output
  exit if json.empty?

  # Get info about formula
  info = json.first
  formula = info['formula']
  stable = Formula[formula].stable
  is_git = stable.downloader.is_a? GitDownloadStrategy

  # Prepare tag and revision or url
  if is_git
    dir = "/tmp/#{formula}"
    tag = stable.specs[:tag].gsub stable.version, info['version']['latest']
    safe_system 'git', 'clone', '--depth', '1', '--branch', tag, stable.url, dir
    revision = Utils.popen_read('git', '-C', dir, 'rev-parse', 'HEAD').chomp
  else
    url = stable.url.gsub stable.version, info['version']['latest']
  end

  puts <<~EOS
    OLD:
      url: #{stable.url}
      tag: #{stable.specs[:tag]}
      revision: #{stable.specs[:revision]}
    NEW:
      url: #{url}
      tag: #{tag}
      revision: #{revision}
  EOS

  print "==> Continue?"
  STDIN.readline

  # Finally bump the formula
  safe_system HOMEBREW_BREW_FILE, 'bump-formula-pr',
       '--no-audit',
       '--no-browse',
       *("--url=#{url}" unless is_git),
       *("--tag=#{tag}" if is_git),
       *("--revision=#{revision}" if is_git),
       formula
end
