#!/bin/bash

set -euo pipefail

git checkout master

for pr in $@; do
    brew pull \
        --bottle \
        --bintray-org "$USER" \
        --test-bot-user "$USER" \
        "https://github.com/dawidd6/homebrew-tap/pull/$pr"
done