#!/bin/bash

set -euo pipefail

TAP="$USER/homebrew-tap"

cd "$(brew --repository $TAP)"

git checkout master

brew pull \
    --bottle \
    --bintray-org=$USER \
    --test-bot-user=$USER \
    "https://github.com/$TAP/pull/$1"
