#!/bin/bash

set -euo pipefail

git add-upstream
git fetch upstream

gbp import-ref -u $1
gbp dch -D xenial -N $1-1
git add debian/changelog
git commit -S -m "d/changelog: dch $1"
git buildpackage --git-tag
