#!/bin/bash

set -euo pipefail

upstream="$(curl -s "https://api.github.com/repos/${USER}/${1}" | jq -r '.parent.clone_url')"
repo="$1"

git clone "git@github.com:${USER}/${repo}.git"

cd "$repo"

git remote add upstream "$upstream"
